"""Database module for Neo4j operations."""

from .neo4j_client import Neo4jClient, neo4j_client
from .operations import (
    create_job,
    create_jobs_bulk,
    create_skill,
    create_skills_bulk,
    create_job_skill_relationship,
    create_job_skill_relationships_bulk,
    create_skill_hierarchy,
    create_skill_hierarchies_bulk,
    get_skill_by_name,
    get_all_skills,
    find_similar_skills,
    get_job_by_id,
    get_jobs_by_skills,
    get_candidate_job_titles,
    get_skills_by_job_titles,
    get_skills_by_job_title,
    search_skills,
    search_jobs_fulltext,
)

__all__ = [
    "Neo4jClient",
    "neo4j_client",
    "create_job",
    "create_jobs_bulk",
    "create_skill",
    "create_skills_bulk",
    "create_job_skill_relationship",
    "create_job_skill_relationships_bulk",
    "create_skill_hierarchy",
    "create_skill_hierarchies_bulk",
    "get_skill_by_name",
    "get_all_skills",
    "find_similar_skills",
    "get_job_by_id",
    "get_jobs_by_skills",
    "get_candidate_job_titles",
    "get_skills_by_job_titles",
    "get_skills_by_job_title",
    "search_skills",
    "search_jobs_fulltext",
]
