# Generated by Django 5.2.8 on 2025-11-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
